name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rabota:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: clang
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl  

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y cmake
        sudo apt-get install rpm

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    # - name: Configure CMake
    #   run: cmake  -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'ubuntu-latest'
      run: |
        cpack -G DEB 
        cpack -G RPM
          matrix.os == 'windows-latest'
      run: |
        cpack -G WIX
      if: matrix.os == 'macos-latest'
      run: |
        cpack -G DragNDrop  
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: ubuntu-pack
        path: |
          build/*.deb
          build/*.rpm
      if: matrix.os == 'windows-latest'
      with:
        name: win-pack
        path: build/*.msi
      if: matrix.os == 'macos-latest'
      with:
        name: macos-pack
        path: build/*.dmg

  create_release:
    needs: [rabota]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: download_ubuntu
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-pack
        path: artifacts/linux

    - name: download_windows
      uses: actions/download-artifact@v4
      with:
        name: win-pack
        path: artifacts/windows

    - name: download_macos
      uses: actions/download-artifact@v4 
      with:
        name: macos-pack
        path: artifacts/macos

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: |
          artifacts/linux/*.deb
          artifacts/linux/*.rpm
          artifacts/windows/*.msi
          artifacts/macos/*.dmg 
          

    # - name: Create Release
    #   if: matrix.os == 'ubuntu-latest'
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: v1.${{ github.run_number }}
    #     name: Release v1.${{ github.run_number }}
    #     files: build/*.deb
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

